### ISSUE TITLE
Crashes after Splash Screen/Logo

### ISSUE THREAD

**Issue by HeinousGames** [raeleus/Particle-Park#1]
Version 2 crashes after it displays the logo. Here is the log when trying to run the jar from terminal:

2019-02-07 19:41:33.402 java[69492:2792994] pid(69492)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
2019-02-07 19:41:33.575 java[69492:2792994] WARNING: NSWindow drag regions should only be invalidated on the Main Thread! This will throw an exception in the future. Called from (
	0   AppKit                              0x00007fff351e9ccc -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 386
	1   AppKit                              0x00007fff351e707c -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1488
	2   AppKit                              0x00007fff351e6aa6 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 45
	3   libglfw.dylib                       0x00000001254a36b6 libglfw.dylib + 63158
	4   libglfw.dylib                       0x000000012549da06 libglfw.dylib + 39430
	5   ???                                 0x00000001100839f4 0x0 + 4563941876
)
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.lwjgl.glfw.GLFW.glfwShowWindow(GLFW.java:2460)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.setVisible(Lwjgl3Window.java:234)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:396)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:380)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:108)
	at com.ray3k.particlepark.desktop.DesktopLauncher.main(DesktopLauncher.java:20)
Caused by: java.lang.IllegalStateException: Please run the JVM with -XstartOnFirstThread and make sure a window toolkit other than GLFW (e.g. AWT or JavaFX) is not initialized.
	at org.lwjgl.glfw.EventLoop$OnScreen.<clinit>(EventLoop.java:63)
	... 6 more

I am on a mac running OS 10.14.2

**Comment by raeleus** [comment]
Thanks for the report! I forgot to take the usual precautions when working with LWJGL3 and Mac. I'll have a resolution soon. Sorry for the inconvenience!

**Comment by chelinho139** [comment]
Having the same problem in my Mac.
2020-11-13 23:34:33.116 java[44165:1145475] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff33580b57 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6c2335bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff335a934c -[NSException raise] + 9
	3   AppKit                              0x00007fff307a35ec -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 310
	4   AppKit                              0x00007fff3078b052 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1416
	5   AppKit                              0x00007fff3078aac3 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
	6   libglfw.dylib                       0x000000012b29c6b6 libglfw.dylib + 63158
	7   libglfw.dylib                       0x000000012b296a06 libglfw.dylib + 39430
	8   ???                                 0x00000001136386b0 0x0 + 4620256944
	9   ???                                 0x00000001136329d0 0x0 + 4620233168
)
libc++abi.dylib: terminating with uncaught exception of type NSException
